### ISSUE TITLE
Passing a folder of images to the flask version never loads them.

### ISSUE THREAD

**Issue by tcapelle** [Britefury/django-labeller#3]
Passing a user defined folder with images never loads them...

```bash
> python -m image_labelling_tool.flask_labeller --images_pat=<images_directory>/*.<jpg|png>
```

The issue appears to be that the program hangs on loading the "non existent" json files.

**Comment by Britefury** [comment]
Thanks for reporting this.
Should be fixed now. Sorry about that.

**Comment by tcapelle** [comment]
that was fast!
I am really liking this little lib, would like to contribute.
