### ISSUE TITLE
DockerFile

### ISSUE THREAD

**Issue by tcapelle** [Britefury/django-labeller#4]
Do you have a dockerfile for this repo?
I can try to make one.
Thanks

**Comment by Britefury** [comment]
No, I don't, but I'd be happy for you to contribute one.
My focus was on making something easy to incorporate into larger applications, so I haven't looked at this angle.

**Comment by tcapelle** [comment]
I am having a little trouble with the host port, it appears that you need to set the port on 0.0.0.0 inside the container, do you know what I need to modify to do this?
- Regarding flask, I am not an expert, but why you did not use the flask command to run the app? (construct the app in the `__init__.py` for instance?)

**Comment by Britefury** [comment]
I'm afraid I haven't got a enough experience with Docket to be able to help I'm afraid.

I'm starting the flask app in the way I do because it's the 'old-school' way of doing things. The `flask` command was introduced sometime after I started writing this library!

**Comment by tcapelle** [comment]
I will probably fork your repo and start with a minimal flask version of it. Also add fastai in the loop to replace the dextr trianing that is not up to date.
